<template>
<div>
<PageHeader eyebrow="Specialty clinics" title="Clinics" description="Clinic visits add longitudinal treatment and clinical evidence to the same permanent patient EHR."><BaseButton :disabled="!selected" @click="open=true"><template #icon><Plus :size="16"/></template>New clinic visit</BaseButton></PageHeader>
<div class="grid gap-6 xl:grid-cols-[300px_1fr]">
<aside class="card p-5"><h2 class="section-title text-base">Registered patients</h2><p class="muted mt-1">Find the existing patient before creating a clinic visit.</p><PatientLookup v-model="selected" :patients="patients" class="mt-4" label="" placeholder="Search name / ID / NIC"/><div v-if="selected" class="mt-4 rounded-xl bg-slate-50 p-3"><p class="text-xs text-slate-400">Selected EHR</p><p class="mt-1 text-sm font-bold">{{selected.firstName}} {{selected.lastName}}</p><p class="text-xs text-slate-400">{{selected.patientNumber}}</p></div></aside>
<main v-if="selected" class="space-y-5"><section class="card p-5"><div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="section-title">Clinic history</h2><p class="muted mt-1">Previous clinic and treatment records remain linked to this patient.</p></div><StatusBadge tone="info" :label="`${history.length} records`"/></div><div class="mt-4 divide-y divide-slate-100"><article v-for="t in history" :key="t.id" class="py-4"><div class="flex justify-between gap-3"><div><StatusBadge tone="info" :label="t.type"/><h3 class="mt-2 font-bold">{{t.treatment}}</h3><p class="text-sm text-slate-500">{{t.diagnosis}}</p></div><span class="text-xs text-slate-400">{{t.date}}</span></div><p class="mt-2 text-sm text-slate-600">{{t.department}} · {{t.doctor}}</p><p v-if="t.notes" class="mt-1 text-sm text-slate-500">{{t.notes}}</p></article><div v-if="!history.length" class="py-8 text-center text-sm text-slate-400">No clinic records yet.</div></div></section></main>
<section v-else class="card grid place-items-center p-16 text-center"><div><div class="mx-auto grid size-14 place-items-center rounded-2xl bg-teal-50 text-teal-700"><Stethoscope :size="26"/></div><h2 class="mt-4 font-bold">Select a registered patient</h2><p class="mt-1 text-sm text-slate-400">Clinic history will appear here.</p></div></section>
</div>
<Modal :open="open" title="New clinic visit" description="The visit is saved as source EHR data for this patient." @close="open=false"><form v-if="selected" @submit.prevent="save" class="grid gap-4 sm:grid-cols-2"><div class="sm:col-span-2 rounded-xl bg-teal-50 p-4 font-bold text-teal-900">{{selected.firstName}} {{selected.lastName}} · {{selected.patientNumber}}</div><FormField label="Clinic / specialty" required><BaseSelect v-model="f.department"><option>Orthopedic Clinic</option><option>Cardiology Clinic</option><option>Diabetic Clinic</option><option>Dermatology Clinic</option><option>ENT Clinic</option><option>General Medicine Clinic</option></BaseSelect></FormField><FormField label="Doctor" required><BaseInput v-model="f.doctor" required/></FormField><div class="sm:col-span-2"><FormField label="Diagnosis" required><BaseInput v-model="f.diagnosis" required/></FormField></div><div class="sm:col-span-2"><FormField label="Treatment / plan"><BaseTextarea v-model="f.treatment"/></FormField></div><FormField label="Body region"><BaseInput v-model="f.bodyRegion" placeholder="Right arm, chest..."/></FormField><FormField label="Clinical finding"><BaseInput v-model="f.clinicalFinding" placeholder="Scar, birthmark, etc."/></FormField><FormField label="Implant / device"><BaseInput v-model="f.implant" placeholder="Orthopedic plate, pacemaker..."/></FormField><FormField label="Old fracture"><BaseInput v-model="f.oldFracture"/></FormField><div class="sm:col-span-2"><FormField label="Clinical notes"><BaseTextarea v-model="f.notes"/></FormField></div><div class="sm:col-span-2 flex justify-end gap-2 border-t pt-4"><BaseButton variant="secondary" type="button" @click="open=false">Cancel</BaseButton><BaseButton type="submit">Save clinic visit</BaseButton></div></form></Modal>
</div>
</template>
<script setup lang="ts">
import {computed,reactive,ref} from 'vue';import {Plus,Stethoscope} from 'lucide-vue-next';import PageHeader from '../components/PageHeader.vue';import BaseButton from '../components/ui/BaseButton.vue';import BaseInput from '../components/ui/BaseInput.vue';import BaseSelect from '../components/ui/BaseSelect.vue';import BaseTextarea from '../components/ui/BaseTextarea.vue';import StatusBadge from '../components/ui/StatusBadge.vue';import FormField from '../components/forms/FormField.vue';import PatientLookup from '../components/patient/PatientLookup.vue';import Modal from '../components/Modal.vue';import {useEHR} from '../stores/ehr'
const {patients,treatmentsForPatient,addTreatment}=useEHR();const selected=ref<any>(null),open=ref(false);const f=reactive({department:'Orthopedic Clinic',doctor:'',diagnosis:'',treatment:'',notes:'',bodyRegion:'',clinicalFinding:'',implant:'',oldFracture:''});const history=computed(()=>selected.value?treatmentsForPatient(selected.value.id).filter(t=>t.type==='CLINIC'):[]);function save(){if(!selected.value)return;addTreatment({patientId:selected.value.id,type:'CLINIC',date:new Date().toISOString().slice(0,10),...f});open.value=false;Object.assign(f,{department:'Orthopedic Clinic',doctor:'',diagnosis:'',treatment:'',notes:'',bodyRegion:'',clinicalFinding:'',implant:'',oldFracture:''});alert('Clinic visit saved to patient EHR.')}
</script>
