<template>
<div>
<PageHeader eyebrow="Emergency department" title="Emergency cases" description="An unidentified patient can enter the emergency workflow without creating a second identity record."><BaseButton @click="open=true"><template #icon><Plus :size="16"/></template>New emergency case</BaseButton></PageHeader>
<div class="grid gap-4 sm:grid-cols-3"><StatCard label="Active cases" :value="emergencies.length"/><StatCard label="Unidentified" :value="unidentified"/><StatCard label="Identified/admitted" :value="emergencies.length-unidentified"/></div>
<div class="mt-6 space-y-3"><div v-for="e in emergencies" :key="e.id" class="card p-5"><div class="flex flex-col justify-between gap-3 sm:flex-row"><div><b>{{e.id}} · {{e.description}}</b><p class="mt-1 text-xs text-slate-400">{{e.arrival}} · {{e.department}}</p></div><div class="flex items-center gap-2"><StatusBadge :label="e.status" :tone="e.status==='UNIDENTIFIED'?'warning':'success'"/><RouterLink v-if="e.status==='UNIDENTIFIED'" to="/ecis"><BaseButton variant="secondary" size="sm">Search ECIS</BaseButton></RouterLink></div></div></div></div>
<Modal :open="open" title="New emergency case" description="Patient ID is optional until identity is established." @close="open=false"><form @submit.prevent="save" class="grid gap-4 sm:grid-cols-2"><div class="sm:col-span-2"><FormField label="Clinical description" required><BaseInput v-model="f.description" required /></FormField></div><FormField label="Department" required><BaseInput v-model="f.department" required /></FormField><FormField label="Status"><BaseSelect v-model="f.status"><option>UNIDENTIFIED</option><option>IDENTIFIED</option><option>ADMITTED</option></BaseSelect></FormField><div class="sm:col-span-2"><FormField label="Known patient (optional)"><BaseSelect v-model="f.patientId"><option value="">Unknown</option><option v-for="p in patients" :key="p.id" :value="p.id">{{p.patientNumber}} — {{p.firstName}} {{p.lastName}}</option></BaseSelect></FormField></div><div class="sm:col-span-2 flex justify-end"><BaseButton type="submit">Create emergency case</BaseButton></div></form></Modal>
</div>
</template>
<script setup lang="ts">
import {computed,reactive,ref} from 'vue';import {RouterLink} from 'vue-router';import {Plus} from 'lucide-vue-next';import PageHeader from '../components/PageHeader.vue';import StatCard from '../components/StatCard.vue';import Modal from '../components/Modal.vue';import BaseButton from '../components/ui/BaseButton.vue';import BaseInput from '../components/ui/BaseInput.vue';import BaseSelect from '../components/ui/BaseSelect.vue';import StatusBadge from '../components/ui/StatusBadge.vue';import FormField from '../components/forms/FormField.vue';import {useEHR} from '../stores/ehr';const {emergencies,patients,addEmergency}=useEHR();const open=ref(false),unidentified=computed(()=>emergencies.value.filter(e=>e.status==='UNIDENTIFIED').length),f=reactive<any>({description:'',department:'Emergency',status:'UNIDENTIFIED',patientId:''});function save(){addEmergency({arrival:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}),...f,patientId:f.patientId||undefined});open.value=false;Object.assign(f,{description:'',patientId:''})}
</script>
