<template>
<div><PageHeader eyebrow="Reporting" title="Reports" description="Operational overview for the hospital system."><BaseButton variant="secondary" @click="refresh">Refresh data</BaseButton></PageHeader>
<div class="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><StatCard label="Patients" :value="patients.length"/><StatCard label="Clinical records" :value="treatments.length"/><StatCard label="Total beds" :value="totalBeds"/><StatCard label="Emergency cases" :value="emergencies.length"/></div>
<div class="mt-6 grid gap-5 lg:grid-cols-2"><section class="card p-5"><h2 class="section-title">Ward occupancy</h2><div class="mt-5 space-y-4"><div v-for="w in wards" :key="w.id"><div class="mb-1 flex justify-between text-xs"><b>{{w.name}}</b><span>{{occ(w)}} / {{w.capacity}}</span></div><div class="h-2 rounded-full bg-slate-100"><div class="h-2 rounded-full bg-teal-600" :style="{width:`${occ(w)/w.capacity*100}%`}"></div></div></div></div></section><section class="card p-5"><h2 class="section-title">ECIS readiness</h2><div class="mt-5 grid gap-3 sm:grid-cols-2"><div class="rounded-xl bg-teal-50 p-4"><p class="text-xs text-teal-700">Patients with treatment history</p><b class="text-2xl text-teal-900">{{withHistory}}</b></div><div class="rounded-xl bg-amber-50 p-4"><p class="text-xs text-amber-700">Unidentified cases</p><b class="text-2xl text-amber-900">{{unidentified}}</b></div></div></section></div>
</div>
</template>
<script setup lang="ts">
import {computed} from 'vue';import BaseButton from '../components/ui/BaseButton.vue';import PageHeader from '../components/PageHeader.vue';import StatCard from '../components/StatCard.vue';import {useEHR} from '../stores/ehr';const {patients,treatments,wards,emergencies,refresh}=useEHR();const totalBeds=computed(()=>wards.value.reduce((n,w)=>n+w.capacity,0));const withHistory=computed(()=>patients.value.filter(p=>treatments.value.some(t=>t.patientId===p.id)).length);const unidentified=computed(()=>emergencies.value.filter(e=>e.status==='UNIDENTIFIED').length);function occ(w:any){return w.beds.filter((b:any)=>b.status==='OCCUPIED').length}
</script>
