<template>
<div><PageHeader eyebrow="Clinical procedures" title="Surgery & Procedures" description="This workflow demonstrates how permanent clinical findings become part of the patient's searchable history."><RouterLink to="/patients"><BaseButton>Find patient</BaseButton></RouterLink></PageHeader>
<div class="card p-5"><h2 class="section-title">Why this matters to ECIS</h2><div class="mt-4 grid gap-3 md:grid-cols-3"><div v-for="x in points" :key="x[0]" class="rounded-xl bg-slate-50 p-4"><p class="font-bold">{{x[0]}}</p><p class="mt-1 text-sm text-slate-500">{{x[1]}}</p></div></div></div>
<div class="mt-5 card overflow-hidden"><div class="border-b p-5"><h2 class="section-title">Recent procedure records</h2></div><div class="divide-y"><div v-for="t in surgery" :key="t.id" class="p-5"><b>{{patientName(t.patientId)}}</b><p class="mt-1 text-sm">{{t.treatment}} · {{t.bodyRegion || 'Body region not recorded'}}</p><div class="mt-2 flex flex-wrap gap-2"><span v-if="t.implant" class="badge">Implant: {{t.implant}}</span><span v-if="t.scar" class="badge">Scar: {{t.scar}}</span><span v-if="t.oldFracture" class="badge">Fracture: {{t.oldFracture}}</span></div></div></div></div>
</div>
</template>
<script setup lang="ts">
import {computed} from 'vue';import {RouterLink} from 'vue-router';import BaseButton from '../components/ui/BaseButton.vue';import PageHeader from '../components/PageHeader.vue';import {useEHR} from '../stores/ehr';const {patients,treatments}=useEHR();const surgery=computed(()=>treatments.value.filter(t=>t.type==='SURGERY'||t.type==='PROCEDURE'));const patientName=(id:string)=>{const p=patients.value.find(x=>x.id===id);return p?`${p.firstName} ${p.lastName} · ${p.patientNumber}`:'Unknown'};const points=[['Surgery','Stores procedure and body region in the patient EHR.'],['Clinical findings','Scar, fracture, implant and missing body-part information can be recorded.'],['ECIS','Later, these existing records become searchable clues for an unidentified patient.']]
</script>
